### ISSUE TITLE
Not detected on Nitrado hosted server

### ISSUE THREAD

**Issue by Leonartorfighter** [Stephen-Cherry/AutoFeed#1] opened 2024-06-21 14:55 UTC
Its impossible to make it work on nitrado servers. and no i dont have valheim plus installed. i have jotun and the newest version on the server inside the plugin folder and it does not work

**Comment by Stephen-Cherry** [comment] 2024-06-21 15:14
@Leonartorfighter Thanks for reporting.  Have you checked to see if it works on a single-player world?  Has it ever worked on your server?  If you check your server logs, do you see a BepInEx message similar to this:

 ```cmd
 [Info   :   BepInEx] Loading [Narolith.AutoFeed 0.2.3]
 ```
 
 Any additional information you can provide may help me try to reproduce it and troubleshoot, thanks!

**Comment by Leonartorfighter** [comment] 2024-06-21 15:32
Give me a bit time looking into everything

**Comment by Leonartorfighter** [comment] 2024-06-21 16:36
![Bild_2024-06-21_183634563](https://github.com/Stephen-Cherry/AutoFeed/assets/173480638/9508f837-bf6f-492f-b811-84a495f1960c)

**Comment by Leonartorfighter** [comment] 2024-06-21 16:37
it works in singleplayer. when i want to join the server this pops up. i habe the newest version on server and client.

**Comment by Leonartorfighter** [comment] 2024-06-21 16:38
and i cant look into the launch files of the server because its not possible on nitrado servers

**Comment by Stephen-Cherry** [comment] 2024-06-21 16:43
It appears the server isn't detecting the mod(s). Do you have any other mod working on your server? You may need to reach out to Nitrado customer support to see if they can help resolve the issue.

**Comment by Stephen-Cherry** [comment] 2024-06-22 04:15
Since this is an issue on the server side with Nitrado and not the mod itself, I'm going to close this issue.  Feel free to let me know if you think there is something I can help with.

**Closed as not planned by Stephen-Cherry** 2024-06-22 04:15 UTC
